# BASICS OF PYTHON | SESSION 1&2

---
Sina Shafiezadeh | October 2024
---


# FAQ

1.   what is programming?

  Programming refers to the process of designing and writing instructions that a computer can understand and execute. It involves creating code using a specific programming language to create software programs, applications, and scripts that can perform various tasks.

2.   what is object-oriented programming?

  Object-oriented programming (OOP) is a programming paradigm that is based on the concept of objects, which can contain data and methods that act on that data. In OOP, objects are instances of classes, which define the structure and behavior of the objects.

3. what is Python?

  Python is a high-level, interpreted programming language that is widely used for web development, scientific computing, data analysis, artificial intelligence, and many other applications. It was created by Guido van Rossum and first released in 1991.

4. why should I learn Python?

*   Versatility: Python can be used for a wide range of applications, including web development, scientific computing, data analysis, artificial intelligence, machine learning, and many more.
*   Simplicity: Python has a simple syntax and is easy to read and write, making it a good choice for beginners.
*   Large community: Python has a large and active community of developers who create third-party libraries and tools, making it easy to find solutions to common problems.
*   Open-source: Python is free and open-source, which means that you can use it for any purpose without having to pay for it.
*   Simplicity

5. how can I coding Python?

*   Go to the official [Python](https://www.python.org/downloads/) website and the [Anaconda](https://www.anaconda.com/) website.
*   Or using the [Google Colab](https://colab.research.google.com/).
*   Or any other tools that you want.

6. what is Google Colab?

  Google Colab (short for Collaboratory) is a free online platform provided by Google that allows users to run Python code and execute Jupyter notebooks directly in the cloud. It is a popular tool for data scientists, machine learning engineers, and researchers who want to develop and experiment with machine learning models without the need for specialized hardware.

7. Do you have more questions?

  Ask from [ChatGPT](https://chat.openai.com/chat) or [Gemini](https://gemini.google.com/app) or any other generative tools you like as I asked to provide previous answers, connect with others in [stackoverflow](https://stackoverflow.com/), search your concerns in Google, and watch a lot of useful videos on Youtube for free!

# Content


*   Day 1:

  *   Create Variables
  *   Conditional Statements
  *   Loops

*   Day 2:

  *   Data Structure
  *   Algorithm

*   Day 3:

  *   Data Importing
  *   Data Cleaning
  *   Data Exploring

*   Day 4:

  *   Data Analysis
  *   Data Visualization
  *   Data Exporting

*   Day 5:

  *   Exam



LET'S START!

# 1.&nbsp;Create Variables

Create a variable with the name `course` and assign the value `"Basic of Python"` after using the `=` sign to the computer to remember information.

In [ ]:
course = "Basic of Python"

we can expand variable names with **Snake Case** format for naming that each word is separated by an underscore character.

In [ ]:
my_course = "Basic of Python"

or using **Camel Case** format for naming that each word, except the first, starts with a capital letter.

In [ ]:
myCourse = "Basic of Python"

or using **Pascal Case** format that each word starts with a capital letter.

In [ ]:
MyCourse = "Basic of Python"

Be careful! Python is a **case-sensitive** programming language, so `MyCourse` and `mycourse` are two different variables.

In [ ]:
mycourse

NameError: name 'mycourse' is not defined

Besides, we can't use **space** for the variable's name.

In [ ]:
My Course = "Basic of Python"

SyntaxError: invalid syntax (<ipython-input-6-2dedfb1ae473>, line 1)

It's better to choose a variable's name to help us understand what's inside a variable. In our case, it's easier to change the variable's name to `course_name`.

In [ ]:
course_name = "Basic of Python"

Finally, we can also define a variable name using **numbers**. It sometimes could be very useful.

In [ ]:
course_1_name = "Basic of Python"
course_2_name = "Cognitive Neuroscience"

Or mix with variable type, in this case, means string (str)

In [ ]:
course_name_str = "Basic of Python"

Great! Let's look at the value on the right side. We store words in double quotes `"   "`, therefore it is a **string**. Strings can contain all sorts of letters and symbols.

In [ ]:
course_name = "Basic of Python"

We ask Python to display a value by `print()` in the console, also known as the shell.

In [ ]:
print(course_name)

Basic of Python


We can repeat `print()` as often as we want and display every value on a line.

In [ ]:
print("=================================")
print("The course's name is:")
print(course_name)
print("=================================")

The course's name is:
Basic of Python


Before continuing this part, let's look at an important point. Python is an **interpreted language** and It means code is run there line by line. Please correct the following code.

In [ ]:
print(universiy_name)
universiy_name = "University of Padova"

NameError: name 'universiy_name' is not defined

We can use this point to update variables. Please guess what will display in the console before running the code.


In [ ]:
course_name = "Cognitive Neuroscience"
print(course_name)
course_name = "Basic of Python"
print(course_name)

Cognitive Neuroscience
Basic of Python


We can add string values together with the `+` sign.

In [ ]:
print("Course name: " + "Basic of Python")
print("Course name: " + course_name)

Course name: Basic of Python
Course name: Basic of Python


Let's cross strings. We can store a **number** in a variable without using `"   "`.

In [ ]:
course_score = 80

Add numbers together by `+`.

In [ ]:
course_score = 80 + 10
print(course_score)

90


Subtract the numbers by `-`.

In [ ]:
course_score = 80 - 10
print(course_score)

70


Multiply numbers by `*`.

In [ ]:
course_score = 80 * 1.5
print(course_score)

120.0


Or divided by `/`.

In [ ]:
course_score = 80 / 8
print(course_score)

10.0


Modulus by `%`.

In [ ]:
course_score = 8 % 5
print(course_score)

3


Exponentiation by `**`.

In [ ]:
course_score = 8 ** 2
print(course_score)

64


And floor division is calculated by `//`.

In [ ]:
course_score = 8 // 5
print(course_score)

1


Keep the variable's value and change only the console by manipulating the `print()`.

In [ ]:
course_score = 80
print(course_score / 8)
print(course_score)

10.0
80


Calculate results and store them in variables. Notice when we want to print a string and a number together in the `print()`, we must use `,` instead of `+` or using f-strings like `f" {} "` to add a variable in a string.

In [ ]:
homework_1_score = 40
homework_2_score = 45
course_score = homework_1_score + homework_2_score
print("course score: " , course_score)
print(f"course score:  {course_score}")

course score:  85
course score:  85


Here is a question. How can we understand the type of our variable? the answer is using `type()`.

In [ ]:
course_score = 80
print(type(course_score))

<class 'int'>


In [ ]:
course_score = 80.0
print(type(course_score))

<class 'float'>


In [ ]:
course_score = "80"
print(type(course_score))

<class 'str'>


Another question: How can we specify a variable type? The answer is casting by `int()`, `float()`, and `str()`.

In [ ]:
course_1_score = int(80)   # will be 80
course_2_score = int(80.7) # will be 80 (not 81)
course_3_score = int("80") # will be 80

course_4_score = float(80)   # will be 80.0
course_5_score = float(80.7) # will be 80.7
course_6_score = float("80") # will be 80.0
course_7_score = float("80.2") # will be 80.2

course_8_score = str(80)   # will be '80'
course_9_score = str(80.7) # will be '80.7'

print("course_1_score:", course_1_score, "\t", type(course_1_score)) # "\t" add space between outputs
print("course_2_score:", course_2_score, "\t", type(course_2_score))
print("course_3_score:", course_3_score, "\t", type(course_3_score))
print("course_4_score:", course_4_score, "\t", type(course_4_score))
print("course_5_score:", course_5_score, "\t", type(course_5_score))
print("course_6_score:", course_6_score, "\t", type(course_6_score))
print("course_7_score:", course_7_score, "\t", type(course_7_score))
print("course_8_score:", course_8_score, "\t", type(course_8_score))
print("course_9_score:", course_9_score, "\t", type(course_9_score))

course_1_score: 80 	 <class 'int'>
course_2_score: 80 	 <class 'int'>
course_3_score: 80 	 <class 'int'>
course_4_score: 80.0 	 <class 'float'>
course_5_score: 80.7 	 <class 'float'>
course_6_score: 80.0 	 <class 'float'>
course_7_score: 80.2 	 <class 'float'>
course_8_score: 80 	 <class 'str'>
course_9_score: 80.7 	 <class 'str'>


Before finishing this part, let's review two important general points. First, Python uses **indentation** to indicate a block of code. Indentation refers to the spaces at the beginning of a code line. Please correct the following code.

In [ ]:
course_score = 80
print(course_score)

80


Secondly, we can use `#` to add **comments** to our code. This helps with the readability and documentation of our code.

In [ ]:
# the range of course scores is between 0 and 100
course_score = 80
print(course_score)

80


That's it! Let's try all the previous points to develop your first exercise.

## Exercise 1 part 1

---


Calculate your BMI score and show your name and score in the console.

*   Expected output 1: My name is Sara and my BMI score is 28.
*   Expected output 2: My name is John and my BMI score is 22.





In [ ]:
# BMI formula: weight (kg) / height**2 (m)




Good job!

Sometimes we need to show if a feature is switched on or off by useing `True` and `False` values.

In [ ]:
calculated_bmi = True
print(calculated_bmi)

True


In [ ]:
calculated_bmi = False
print(calculated_bmi)

False


Besides, we need to compare two values.

In [ ]:
bmi_score = 28
print(bmi_score == 28) # equal
print(bmi_score != 28) # not equal
print(bmi_score > 28)  # greater than
print(bmi_score < 28)  # less than
print(bmi_score >= 28) # greater than or equal to
print(bmi_score <= 28) # less than or equal to

True
False
False
False
True
True


Maybe logical operators to combine conditional statements.

In [ ]:
bmi_score = 28
print(bmi_score > 20 and bmi_score > 30) # returns True if both statements are true
print(bmi_score > 20 or bmi_score > 30) # returns True if one of the statements is true
print(not(bmi_score > 20 and bmi_score > 30)) # reverse the result, returns False if the result is true

False
True
True


## Exercise 1 part 2

---


Check whether your BMI score is normal or not.

*   Expected output 1: True
*   Expected output 2: False





In [ ]:
# normal range is from 18.5 to 24.9






# 2.&nbsp;Conditional Statements

We use the **if statement** to adapt to different situations. Notice to use `:` after the statement and indentation before `print()`.

In [ ]:
bmi_score = 28

if bmi_score < 18.8:
  print("BMI score is under weight.")
else:
  print("BMI score is not under weight.")

BMI score is not under weight.


Maybe we have more than one condition.

In [ ]:
bmi_score = 28

if bmi_score > 18.5 and bmi_score < 24.9:
  print("BMI score is normal.")
else:
  print("BMI score is not normal.")

BMI score is not normal.


In [ ]:
bmi_score = 28

if bmi_score < 18.5 or bmi_score > 24.9:
  print("BMI score is not normal.")
else:
  print("BMI score is normal.")

BMI score is not normal.


Or we have more than two situations.

In [ ]:
bmi_score = 28

if bmi_score < 18.8:
  print("BMI score is under weight.")
elif bmi_score > 18.5 and bmi_score < 24.9:
  print("BMI score is under normal.")
elif bmi_score > 25 and bmi_score < 29.9:
  print("BMI score is over weight.")
elif bmi_score > 30 and bmi_score < 39.9:
  print("BMI score is obesity.")
else:
  print("BMI score is extreme obesity.")

BMI score is over weight.


## Exercise 2

---


We want to predict the BMI score after doing sport routing over one year. Assume the one-month sport reduces the 0.38 value from the BMI score. What will happen to BMI score if someone does sports for 3, 6, 9, and 12 months?

*   Expected output 1: BMI score will be 27.76 after 3 months of sports.
*   Expected output 2: BMI score will be 24.91 after 12 months of sports





In [ ]:
# try with different values
bmi_score = 28.4
sport_duration = 9





# 3.&nbsp;Loops (while)

Using the `while` loop, we can execute a set of statements if a condition is true.

In [ ]:
bmi_score = 21.4

while bmi_score < 25:
  print(f"your BMI score is {bmi_score} (normal range).")
  bmi_score += 1 # bmi_score = bmi_score + 1

your BMI score is 21.4 (normal range).
your BMI score is 22.4 (normal range).
your BMI score is 23.4 (normal range).
your BMI score is 24.4 (normal range).


If the while condition is true, the `break` statement will prevent the loop from continuing indefinitely.

In [ ]:
bmi_score = 21.4

while bmi_score < 25:
  print(f"your BMI score is {bmi_score} (normal range).")
  bmi_score -= 1 # bmi_score = bmi_score - 1
  if bmi_score < 18.8:
    break

your BMI score is 21.4 (normal range).
your BMI score is 20.4 (normal range).
your BMI score is 19.4 (normal range).


Or if the condition is no longer true, an `else` statement will run a block of code once.

In [ ]:
bmi_score = 21.4

while bmi_score > 18.8:
  print(f"your BMI score is {bmi_score} (normal range).")
  bmi_score -= 1
else:
  print(f"your BMI score is {bmi_score} (under weight).")

your BMI score is 21.4 (normal range).
your BMI score is 20.4 (normal range).
your BMI score is 19.4 (normal range).
your BMI score is 18.4 (under weight).


The `continue` statement lets us stop the current iteration and move on to the next.

In [ ]:
bmi_score = 19

while bmi_score < 25:
  bmi_score += 1
  if bmi_score == 22:
    continue
  if bmi_score >= 25:
    break
  print(f"your BMI score is {bmi_score} (normal range).")


your BMI score is 20 (normal range).
your BMI score is 21 (normal range).
your BMI score is 23 (normal range).
your BMI score is 24 (normal range).


## Exercise 3

---

We assumed the one-month sport reduce by 0.38 value from the BMI score. Now, write a `while` loop to calculate the maximum number of months to reach the normal range for BMI score.

*   Expected output 1: you need 3 months of sport
*   Expected output 2: you need 7 months of sport





In [ ]:
# try different BMI score
bmi_score = 28.6
sport_duration = 0




# 4.&nbsp;Loops (for)

Excellent! Let's look at the `for` loop.

Using the `for` loop means we know how many times we need to execute a statement, so we can use it when we know how many iterations there will be. In addition, `range()` returns a sequence of numbers starting from 0 and incrementing by 1 by default, and ending at a specified number. Although, we can change default values if we want.

In [ ]:
bmi_score = 19

for i in range(3):
  print(f"your BMI score is {bmi_score} (normal range).")
  bmi_score += 1

your BMI score is 19 (normal range).
your BMI score is 20 (normal range).
your BMI score is 21 (normal range).


Besides, while loop's statements including the `break`, `continue`, and `else` could be used here as well.

In [ ]:
bmi_score = 19

for i in range(5):
  bmi_score += 1
  if bmi_score == 22:
    continue
  print(f"your BMI score is {bmi_score} (normal range).")

your BMI score is 20 (normal range).
your BMI score is 21 (normal range).
your BMI score is 23 (normal range).
your BMI score is 24 (normal range).


In [ ]:
bmi_score = 19

for i in range(6):
  print(f"your BMI score is {bmi_score} (normal range).")
  bmi_score += 1
  if bmi_score == 25:
    break

your BMI score is 19 (normal range).
your BMI score is 20 (normal range).
your BMI score is 21 (normal range).
your BMI score is 22 (normal range).
your BMI score is 23 (normal range).
your BMI score is 24 (normal range).


In [ ]:
bmi_score = 19

for i in range(6):
  print(f"your BMI score is {bmi_score} (normal range).")
  bmi_score += 1
else:
  print(f"your BMI score is {bmi_score} (Over weight).")

your BMI score is 19 (normal range).
your BMI score is 20 (normal range).
your BMI score is 21 (normal range).
your BMI score is 22 (normal range).
your BMI score is 23 (normal range).
your BMI score is 24 (normal range).
your BMI score is 25 (Over weight).


## Exercise 4

---


Similar to the previous exercise we assumed the one-month sport reduce 0.38 value from the BMI score. Now, write a `for` loop to calculate finalized BMI score after 7 months of sports.

*   Expected output 1: your BMI score will be 21.93 after 7 months of sport
*   Expected output 2: your BMI score will be 26.77 after 7 months of sport



In [ ]:
# try different BMI score
bmi_score = 28.6
sport_duration = 7







# 5.&nbsp;Data Structure (string and list)

For organization, management, and storage data we need to know different data types and how to work with them. We familiarize ourselves with **integers**, **floats**, and **booleans** before.

In [ ]:
x = 18 # int
y = 24.9 # float
z = True # boolean

We are also familiarized with **string** but let's deep in a little bit on that.

In [ ]:
w = "this is a string"
print(type(w)) # get data type

<class 'str'>


In [ ]:
print(len(w)) # get length

16


In [ ]:
# access item by position
# note: position in Python starts at 0.
w = "this is a string"

print("position 0 : ", w[0])
print("position 1 : ", w[1])
print("position -2: ", w[-2])
print("\n") # create a new line
print("range of position 1: ", w[1:3])
print("range of position 2: ", w[:3])
print("range of position 3: ", w[3:])
print("range of position 4: ", w[:])
print("range of position 5: ", w[-3:-1])
print("range of position 6: ", w[:-1])
print("range of position 7: ", w[-3:])

position 0 :  t
position 1 :  h
position -2:  n


range of position 1:  hi
range of position 2:  thi
range of position 3:  s is a string
range of position 4:  this is a string
range of position 5:  in
range of position 6:  this is a strin
range of position 7:  ing


In [ ]:
# check if item exists
if "this" in w:
  print("Yes, this is in w string.")

Yes, this is in w string.


In [ ]:
print(w.upper()) # upper case

THIS IS A STRING


In [ ]:
print(w.lower()) # lower case

this is a string


In [ ]:
print(w.replace("this", "that")) # replace

that is a string


In [ ]:
print(w.split(" ")) # split by space

['this', 'is', 'a', 'string']


Perfect!

Let's continue with another data type. Using **lists**, we can store multiple items with any type of data in one variable by using `[]` and `,` between items.

In [ ]:
student = ["name", "Weight", "Height", 21.7, True]
print(student)

['name', 'Weight', 'Height', 21.7, True]


In [ ]:
print(type(student)) # get data type

<class 'list'>


In [ ]:
print(len(student)) # get length

5


In [ ]:
# access item by index
# note: indexing in Python starts at 0.
print("index 0 : ", student[0])
print("index 1 : ", student[1])
print("index -2: ", student[-2])
print("\nrange of index 1: ", student[1:3]) # notice to \n
print("range of index 2: ", student[:3])
print("range of index 3: ", student[1:])
print("range of index 4: ", student[:])
print("range of index 5: ", student[-3:-1])
print("range of index 6: ", student[:-1])
print("range of index 7: ", student[-3:])

index 0 :  name
index 1 :  Weight
index -2:  21.7

range of index 1:  ['Weight', 'Height']
range of index 2:  ['name', 'Weight', 'Height']
range of index 3:  ['Weight', 'Height', 21.7, True]
range of index 4:  ['name', 'Weight', 'Height', 21.7, True]
range of index 5:  ['Height', 21.7]
range of index 6:  ['name', 'Weight', 'Height', 21.7]
range of index 7:  ['Height', 21.7, True]


In [ ]:
# check if item exists
if "Height" in student:
  print("Yes, Height is in the student list.")

Yes, Height is in the student list.


In [ ]:
# change item value by index
print(student)
student[3] = 21.4
student[1:3] = ["weight", "height"]
print(student)

['name', 'Weight', 'Height', 21.7, True]
['name', 'weight', 'height', 21.4, True]


In [ ]:
# insert item value by index
student.insert(1, "surname")
print(student)

['name', 'surname', 'weight', 'height', 21.4, True]


In [ ]:
# append item value to the end of the list
student.append("age")
print(student)

['name', 'surname', 'weight', 'height', 21.4, True, 'age']


In [ ]:
# append items from another list to current list
education = ["course", "score"]
student.extend(education)
print(student)

['name', 'surname', 'weight', 'height', 21.4, True, 'age', 'course', 'score']


In [ ]:
# append and extend difference
list_one = [1, 3, 5, 7]
list_two = [9, 11]
list_one.append(list_two)
print("appended list: ", list_one)

list_one = [1, 3, 5, 7]
list_two = [9, 11]
list_one.extend(list_two)
print("extended list: ", list_one)

appended list:  [1, 3, 5, 7, [9, 11]]
extended list:  [1, 3, 5, 7, 9, 11]


In [ ]:
# remove by item value
student.remove("course")
print(student)

['name', 'surname', 'weight', 'height', 21.4, True, 'age', 'score']


In [ ]:
# remove by index
student.pop(-2)
print(student)

['name', 'surname', 'weight', 'height', 21.4, True, 'score']


In [ ]:
# the pop() method removes the last item if you don't specify the index
student.pop()
print(student)

['name', 'surname', 'weight', 'height', 21.4, True]


In [ ]:
# another way to remove by index
del student[1]
print(student)

['name', 'weight', 'height', 21.4, True]


In [ ]:
# loop through a list
for i in student:
  print(i)

name
weight
height
21.4
True


In [ ]:
# loop through the index numbers
for i in range(len(student)):
  print(student[i])

name
weight
height
21.4
True


In [ ]:
# removes all the items from the list
student.clear()
print(student)

[]


In [ ]:
# looping using list comprehension (shortest syntax)
bmi = [21.31, 26.9, 24.1, 29.4]
student_bmi = [i+1 for i in bmi]
print(student_bmi)

[22.31, 27.9, 25.1, 30.4]


In [ ]:
# sort items
student_bmi.sort() # ascending
print(student_bmi)
student_bmi.sort(reverse = True) # descending
print(student_bmi)

[22.31, 25.1, 27.9, 30.4]
[30.4, 27.9, 25.1, 22.31]


## Exercise 5

---


1. Calculate the BMI score for all patients and store it in a list. (Hint: for loop)
2. Remove items in the normal range.  (Hint: if statement)
3. Sort items by descending.

*   Expected output:
        [28.20, 27.52, 25.34]



In [ ]:
patient_name = ["Georgia", "Oscar", "Juliet", "Lily", "William"]
patient_weight = [54.7, 79.6, 81.2, 51.9, 102.5] # kg
patient_height = [152, 168, 179, 161, 193] # cm
patient_bmi = []

# start from here...







# 6.&nbsp;Data Structure (tuple, set and dictionary)

We can group together closely-related data unchangeable using **tuples**. We create them similarly to lists but using parentheses `()` instead of brackets.

In [ ]:
thistuple = ("Georgia", 54.7, 152, False)
print(type(thistuple))

<class 'tuple'>


In [ ]:
print(len(thistuple))

4


In [ ]:
tuple_one_item = ("Georgia",)
print(type(tuple_one_item))

# it is NOT a tuple
tuple_one_item = ("Georgia")
print(type(tuple_one_item))

<class 'tuple'>
<class 'str'>


In [ ]:
# access item by index
print("index 0 : ", thistuple[0])
print("index 1 : ", thistuple[1])
print("index -2: ", thistuple[-2])
print("=================================")
print("range of index 1: ", thistuple[1:3])
print("range of index 2: ", thistuple[:3])
print("range of index 3: ", thistuple[1:])
print("range of index 4: ", thistuple[:])
print("range of index 5: ", thistuple[-3:-1])
print("range of index 6: ", thistuple[:-1])
print("range of index 7: ", thistuple[-3:])

index 0 :  Georgia
index 1 :  54.7
index -2:  152
range of index 1:  (54.7, 152)
range of index 2:  ('Georgia', 54.7, 152)
range of index 3:  (54.7, 152, False)
range of index 4:  ('Georgia', 54.7, 152, False)
range of index 5:  (54.7, 152)
range of index 6:  ('Georgia', 54.7, 152)
range of index 7:  (54.7, 152, False)


In [ ]:
# check if item exists
if "Georgia" in thistuple:
  print("Yes, Georgia is in thistuple.")

Yes, Georgia is in thistuple.


Tuples are **unchangeable**, therefore we should convert them to a list to change, add, or remove an item.

In [ ]:
thislist = list(thistuple) # convert to a list
thislist[0] = "Oscar" # change an item
thislist.append("Brown") # add an item
thislist.remove(152) # remove an item
thistuple = tuple(thislist) # convert to a tuple
print(thistuple)

('Oscar', 54.7, False, 'Brown')


The next data type is **set**. We use a set like a list but use `{}` to make sure values can't have any **duplicates**.

In [ ]:
thisset = {"Georgia", 54.7, 152, False, False}
print(type(thisset))

<class 'set'>


In [ ]:
print(len(thisset)) # remove duplicated False

4


We can not refer to set items by index or key, because sets are **unordered** and they can appear in a different order each time you use them.

In [ ]:
print(thisset)

{152, False, 54.7, 'Georgia'}


Although we can't change values, we are able to **add** or **remove** new values.

In [ ]:
thisset.add("Brown")
thisset.remove(54.7)
print(thisset)

{False, 'Brown', 'Georgia', 152}


Let's familiarize ourselves with another data type called **dictionary**. A dictionary consists of **keys** and **values** and is written in curly brackets `{}`.

In [ ]:
thisdict = {"name": ["Georgia"],
            "bmi": 21.5,
            "normal": True}
print(type(thisdict))

<class 'dict'>


In [ ]:
print(len(thisdict))

3


In [ ]:
# get all the keys
print(thisdict.keys())

dict_keys(['name', 'bmi', 'normal'])


In [ ]:
# get all the values
print(thisdict.values())

dict_values([['Georgia'], 21.5, True])


In [ ]:
# get all the items in tuples
print(thisdict.items())

dict_items([('name', ['Georgia']), ('bmi', 21.5), ('normal', True)])


In [ ]:
# access item by key name
print(thisdict["bmi"])

21.5


In [ ]:
# check if key exists
if "name" in thisdict:
  print("Yes, name is one of the keys in the thisdict")

Yes, name is one of the keys in the thisdict


In [ ]:
thisdict["name"] = "Oscar" # change an item
thisdict["surname"] = "Brown" # add an item
thisdict.pop("bmi") # remove an item
print(thisdict)

{'name': 'Oscar', 'normal': True, 'surname': 'Brown'}


## Exercise 6

---


1. Calculate the BMI score for all patients and store their **name** and **BMI score** in patients_info dictionary.
2. Remove items in the normal range.

*   Expected output:
        patients_info = {"name": ["Oscar", "Juliet", "William"], "bmi": [28, 25, 27]}


In [ ]:
patient_name = ["Georgia", "Oscar", "Juliet", "Lily", "William"]
patient_weight = [54.7, 79.6, 81.2, 51.9, 102.5] # kg
patient_height = [152, 168, 179, 161, 193] # cm
patients_info = {"name":[]
                 ,"bmi":[]}

# start from here...







# 7.&nbsp;Data Structure (module and array)

The last data type we want to know is an **array**. However, we need to know about the **module** first to work with arrays in Python easier.

Modules group related classes and methods to be accessible from one place.

In the following, we import the [numpy](https://numpy.org//) package and modify its name into np to use easier later. Numpy is the fundamental package for scientific computing with Python.

In [ ]:
import numpy as np

We can access an array's values by referring to its index number, and arrays can hold many values.

In [ ]:
# set the seed for reproducibility
np.random.seed(42)

# generate 20 random float values between 18 and 32
bmi_array = np.random.uniform(18, 32, size=20)
bmi_array = np.round(bmi_array, 2)

print(type(bmi_array))

<class 'numpy.ndarray'>


In [ ]:
print(bmi_array)

[23.24 31.31 28.25 26.38 20.18 20.18 18.81 30.13 26.42 27.91 18.29 31.58
 29.65 20.97 20.55 20.57 22.26 25.35 24.05 22.08]


In [ ]:
print(len(bmi_array))

20


In [ ]:
# access item by index
print("index 0 : ", bmi_array[0])
print("index 1 : ", bmi_array[1])
print("index -2: ", bmi_array[-2])
print("\n")
print("=================================")
print("\n")
print("range of index 1: ", bmi_array[1:3])
print("\nrange of index 2: ", bmi_array[:3])
print("\nrange of index 3: ", bmi_array[1:])
print("\nrange of index 4: ", bmi_array[:])
print("\nrange of index 5: ", bmi_array[-3:-1])
print("\nrange of index 6: ", bmi_array[:-1])
print("\nrange of index 7: ", bmi_array[-3:])

index 0 :  23.24
index 1 :  31.31
index -2:  24.05




range of index 1:  [31.31 28.25]

range of index 2:  [23.24 31.31 28.25]

range of index 3:  [31.31 28.25 26.38 20.18 20.18 18.81 30.13 26.42 27.91 18.29 31.58 29.65
 20.97 20.55 20.57 22.26 25.35 24.05 22.08]

range of index 4:  [23.24 31.31 28.25 26.38 20.18 20.18 18.81 30.13 26.42 27.91 18.29 31.58
 29.65 20.97 20.55 20.57 22.26 25.35 24.05 22.08]

range of index 5:  [25.35 24.05]

range of index 6:  [23.24 31.31 28.25 26.38 20.18 20.18 18.81 30.13 26.42 27.91 18.29 31.58
 29.65 20.97 20.55 20.57 22.26 25.35 24.05]

range of index 7:  [25.35 24.05 22.08]


In [ ]:
# 1D array with 5 elements between 18 to 30
arr_1d = np.random.randint(18,30,size=(3))
print(arr_1d.shape)
print(arr_1d)

# 2D array with 3 rows and 4 columns
arr_2d = np.random.randint(18,30,size=(3, 2))
print("\n")
print("==================")
print("\n")
print(arr_2d.shape)
print(arr_2d)


# 3D array with 2 planes, 3 rows, and 2 columns
arr_3d = np.random.randint(18,30,size=(2, 3, 5))
print("\n")
print("==================")
print("\n")
print(arr_3d.shape)
print(arr_3d)


(3,)
[28 27 29]




(3, 2)
[[29 20]
 [29 24]
 [21 26]]




(2, 3, 5)
[[[20 22 20 24 22]
  [26 24 19 21 26]
  [29 19 27 26 27]]

 [[22 19 21 29 29]
  [24 29 25 20 18]
  [21 19 25 21 19]]]


## Exercise 7

---


1. Create two arrays for height (145 to 190 cm) and weight (45 to 120 kg) with 5 float random values.
2. Calculate the BMI score and store it in a list called **calculated_bmi**, at the same time, indicate whether a BMI value is normal or not and store it in a list called **evaluated_bmi**.


*   Expected output:
        calculated_bmi: [31.35, 21.72, 47.07, 34.03, 29.43]
        evaluated_bmi: [False, True, False, False, False]

In [ ]:
# select a reasonable weight and height range as you want
np.random.seed(42)

# start from here...






# 8.&nbsp;Algorithm (function)

**Algorithms** define a set of actions that must be performed in a specific step by step to produce the desired result.

**Functions** help us to implement algorithms. Functions are blocks of code that only run when they are called in situations where we want to reuse existing code without rewriting it.

In [ ]:
# define a function
def first_function():
  print("this is my first function.")

# call a function
first_function()

this is my first function.


We can write our algorithm inside a function and pass value to it.

In [ ]:
def first_function(x):
  x = x + 3
  return x

first_function(x=4)

7

More than one argument we can use in functions.

In [ ]:
def first_function(x,y):
  z = x + y
  return z

first_function(x=4,y=2)

6

It's better to start a function name with a **verb** that explains what will happen in a function.

In [ ]:
def get_sum(x,y):
  z = x + y
  return z

get_sum(x=4,y=2)

6

We can set a default value for arguments.

In [ ]:
def get_sum(x,y=3):
  z = x + y
  return z

get_sum(x=4)

7

In [ ]:
def get_sum(x,y=3):
  z = x + y
  return z

get_sum(x=4,y=2)

6

We can also pass a list to the arguments.

In [ ]:
def get_sum(x,y):
  z = x + y
  return z

x = [3,2,7]
y = [1,4]
get_sum(x,y)

[3, 2, 7, 1, 4]

Or using loops and conditional statements inside functions.

In [ ]:
def get_square(x,y):
  z = x + y
  if len(z) == 0:
    print("your list is empty!")
  else:
    for i in z:
      j = i**2
      print(f"i = {i} and j = {j}")

x = [3,2,7]
y = [1,-4]
get_square(x,y)

i = 3 and j = 9
i = 2 and j = 4
i = 7 and j = 49
i = 1 and j = 1
i = -4 and j = 16


## Exercise 8

---


1. Define a function to calculate BMI score.
2. Store BMI scores into the bmi_score list.
3. Sort items  by descending.

*   Expected output:
        bmi_score = [23.68, 28.20, 25.34, 20.02]

In [ ]:
# patient = [weight(kg), height(cm)]
patient1 = [54.7, 152]
patient2 = [79.6, 168]
patient3 = [81.2, 179]
patient4 = [51.9, 161]
bmi_score = []

# start from here...





# 9.&nbsp;Algorithm (class)

There are many properties and methods in an **object** in Python, and almost everything is an object. **Classes** are like object constructors; we use them to group data and functionality. Functions belonging to objects are called **methods**.

In [ ]:
def get_square(x,y):
  z = x + y
  if len(z) == 0:
    print("your list is empty!")
  else:
    for i in z:
      j = i**2
      print(f"i = {i} and j = {j}")

x = [3,2,7]
y = [1,-4]
get_square(x,y)

i = 3 and j = 9
i = 2 and j = 4
i = 7 and j = 49
i = 1 and j = 1
i = -4 and j = 16


In [ ]:
class Price:
  def __init__(self, value, discount):
    self.value = value
    self.discount = discount

  def summer(self):
    summer_price = round(self.value - (self.value * (self.discount/100)), 2)
    print(summer_price)

  def winter(self):
    winter_price = round(self.value - (self.value * (self.discount * 2/100)), 2) #double discount
    print(winter_price)

#create variables from the class (Price is a "definition" and shoes_price is an "instance")
shoes_price = Price(115, 18) # price 115 euro and 18% discount
shoes_price.summer()
shoes_price.winter()

94.3
73.6


## Exercise 9

---


1. Define a class called BMI and three methods including converting pound to kg, inch to cm, and calculating BMI score.
2. Calculate BMI score for 3 given patients and store them in the bmi_score list.

*   Expected output:
        bmi_score = [23.49, 27.98, 25.14, 19.86]

In [ ]:
# 1 pound ≈ 0.45 kg
# 1 inch ≈ 2.54 cm
# patient = [weight(pond), height(inch)]
patient1 = [120.59, 59.84]
patient2 = [175.49, 66.14]
patient3 = [179.02, 70.47]
patient4 = [114.42, 63.39]
bmi_score = []

# start from here...






# 10.&nbsp;Algorithm (error and exception)

If Python can't understand your code, we will get an **error**! However, we can find our error location by finding `^` in an error message.

In [ ]:
# syntax error (missed variable)
x = 5
if > 3:
  print("Hello")

SyntaxError: invalid syntax (<ipython-input-70-f871c98c446c>, line 3)

In [ ]:
# syntax error (misspelling)
x = 5
iif x > 3:
  print("Hello")

SyntaxError: invalid syntax (<ipython-input-71-a3fc82740201>, line 3)

In [ ]:
# missing indentation error (missed indentation)
x = 5
if x > 3:
print("Hello")

IndentationError: expected an indented block after 'if' statement on line 3 (<ipython-input-73-4affb85865ee>, line 4)

On the other hand, sometimes Python understands our code, but can't execute it. Therefore, it raises an **exception**. The text in the console is called **traceback** and it helps us to **debug** our code.

In [ ]:
# name error
height = cm / 100

NameError: name 'cm' is not defined

In [ ]:
# type error
height = 100 + "56"

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
# zero division error
height = 156 / 0

ZeroDivisionError: division by zero

In [ ]:
# module not found error
import numpyy

ModuleNotFoundError: No module named 'numpyy'

Be careful! Sometimes a module exists but we need to install it.

In [ ]:
!pip install mne
import mne # package for human neurophysiological data analysis

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 39.6 MB/s eta 0:00:00


In [ ]:
# index error
height = [149, 187, 168]
height[3]

IndexError: list index out of range

We can use errors and exceptions to debug our code. Besides, we can use them to avoid **unwanted issues**.

In [ ]:
# test 1: run the code and see the results
# test 2: add "184" to "student_height" and run the code
# test 3: remove "184" from "student_height" and change "179" into "0" and run the code

student_name = ["Georgia", "Oscar", "Juliet", "Lily", "William"]
student_weight = [54.7, 79.6, 81.2, 51.9, 102.5]
student_height = [152, 168, 179, 161, 193]
student_bmi = []

# make sure about data size
if len(student_weight) != len(student_height):
  raise Exception("There must be equal size for weights and hights")

for i in range(len(student_name)):
  # make sure height is not zero
  if student_height[i] == 0:
    raise ValueError("height can not be zero")

  student_bmi.append(round(student_weight[i] / ((student_height[i]/100)**2), 1))

print(student_bmi)

[23.7, 28.2, 25.3, 20.0, 27.5]


Sometimes we don't want to raise an exception and we want to handle it. For example, we want a `for` loop to continue at the end of the code by ignoring negative values for weight, therefore we can use `try` and `except`.

In [ ]:
student_name = ["Georgia", "Oscar", "Juliet", "Lily", "William"]
student_weight = [54.7, 79.6, 81.2, 51.9, 102.5]
student_height = [-152, 168, 0, 161, 193]
student_bmi = []


for i in range(len(student_name)):

  try:
    student_bmi.append(round(student_weight[i] / ((student_height[i]/100)**2), 1))

  except:
    continue

print(student_bmi)

SyntaxError: expected 'except' or 'finally' block (<ipython-input-88-08426f257b18>, line 13)

## Exercise 10

---


1. Copy your exercise 9 code.
2. Set a **type error** to check the heights have float values.
3. Set a value error to make sure the BMI score is not negative.


In [ ]:
# 1 pound ≈ 0.45 kg
# 1 inch ≈ 2.54 cm
# patient = [weight(pond), height(inch)]
patient1 = [120.59, 59.84]
patient2 = [175.49, 66.14]
patient3 = [179.02, 70.47]
patient4 = [114.42, 63.39]
bmi_score = []

# past your code here...









Congratulations! You did it.


# References and Resources:

1. You can continue your learning by more complex data structure and algorithm tasks in [Leetcode](https://leetcode.com/).

2. you can always have access to Python syntax and practical examples in [w3schools](https://www.w3schools.com/python/default.asp) and [geeksforgeeks](https://www.geeksforgeeks.org/python-programming-language/).

3. You can find everything about Numpy to work with arrays [HERE](https://numpy.org/doc/stable/index.html#) and you can also utilize all APIs and documents about Pandas to work with data frames [HERE](https://pandas.pydata.org/docs/index.html#).